sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234


  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tNFKhBVFsjcq95tfmyZ
    access-key-secret: hNkf7auUEsJWxlH4iIpQWmDWKkUArm
    bucket-name: web-framework1010


  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10

  wechat:
    appid: wxda809f303ca8af8d
    secret: cc6317e58332b63b6078444f16c5867d

    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php


